export const pdfStyles = {
  heading: {
    fontSize: 16,
    bold: true,
    alignment: 'left',
    margin: [0, 0, 0, 50],
    color: '#386384',
  },
  firstNameHeader: {
    fontSize: 11,
    bold: true,
    color: '#4B5157',
    margin: [0, 0, 83, 5],
  },
  columnText: {
    fontSize: 11,
    bold: true,
    color: '#040404',
    margin: [0, 0, 83, 5],
  },
  employeeSecondTable: {
    fontSize: 11,
    bold: true,
    color: '#040404',
    margin: [0, 0, 50, 5],
  },
  columnHeader: {
    fontSize: 11,
    bold: true,
    color: '#4B5157',
    margin: [0, 0, 50, 5],
  },
  employeeTableHeader: {
    fontSize: 10,
    bold: true,
    fillColor: '#518EBD',
    margin: [0, 0, 0, 0],
    color: 'white',
    alignment: 'center',
  },
  employeeTableData: {
    fontSize: 9,
    bold: true,
    color: '#040404',
    margin: [0, 0, 0, 5],
    alignment: 'center',
  },
  departmentData: {
    fontSize: 10,
    bold: true,
    fillColor: '#518EBD',
    margin: [18, 0, 18, 0],
    color: 'white',
    alignment: 'center',
  },
  wageData: {
    fontSize: 10,
    bold: true,
    fillColor: '#518EBD',
    margin: [5, 0, 5, 0],
    color: 'white',
    alignment: 'center',
  },
  lastRowTotal: {
    fontSize: 12,
    bold: true,
    fillColor: '#DFEEF9',
    margin: [0, 0, 16, 0],
    color: 'black',
    alignment: 'center',
  },
  dailyTotalValues: {
    fontSize: 11,
    bold: true,
    color: 'black',
    margin: [0, 0, 10, 5],
    alignment: 'center',
  },
  weeklyTotalRow: {
    fontSize: 9,
    bold: true,
    color: '#040404',
    margin: [0, 0, 0, 5],
    alignment: 'center',
    fillColor: '#beddf3',
  },
  summaryHeader: {
    alignment: 'center',
    margin: [0, 25, 0, 8],
    color: 'black',
    bold: true,
    fontSize: 19,
  },
  summarySubheader: {
    alignment: 'center',
    margin: [0, 8, 0, 8],
    color: 'black',
    fontSize: 15,
  },
  summaryTableHeader: {
    color: 'black',
    fontSize: 11,
    bold: true,
    margin: [0, 0, 0, 1],
  },
  summaryTableData: {
    color: 'black',
    fontSize: 10,
    margin: [0, 0, 0, 1]
  },
  summaryTotals: {
    color: 'black',
    fontSize: 11,
    bold: true,
    margin: [0, 0, 0, 1],
    border: [false, false, false, true],
    fillColor:  '#83B4FF'
  }
};
